import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
const isTablet = width >= 768;
const isLargeTablet = width >= 1024;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 8 : 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  headerTablet: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 12 : 20,
    paddingBottom: 16,
  },
  headerContentTablet: {
    flex: 1,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E293B',
  },
  titleTablet: {
    fontSize: 28,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  subtitleTablet: {
    fontSize: 16,
    marginTop: 4,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    margin: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  searchContainerTablet: {
    margin: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    marginRight: 8,
    fontSize: 14,
    color: '#1E293B',
    padding: 0,
  },
  searchInputTablet: {
    marginLeft: 12,
    marginRight: 12,
    fontSize: 16,
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  statsContainerTablet: {
    marginHorizontal: 24,
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 6,
  },
  statItemSelected: {
    backgroundColor: '#F5F3FF',
  },
  statCount: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
    marginTop: 4,
  },
  statCountSelected: {
    color: '#8B5CF6',
  },
  statLabel: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 2,
    textTransform: 'uppercase',
    fontWeight: '500',
  },
  statLabelSelected: {
    color: '#8B5CF6',
    fontWeight: '600',
  },
  rolesList: {
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  rolesListTablet: {
    paddingHorizontal: 24,
  },
  emptyListContainer: {
    flexGrow: 1,
  },
  rolesGridTablet: {
    justifyContent: 'space-between',
    gap: 16,
  },
  roleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  roleCardTablet: {
    flex: 1,
    minWidth: isLargeTablet ? '31%' : '48%',
    marginBottom: 16,
  },
  roleHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  roleIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  employeeIconContainer: {
    backgroundColor: '#FAF5FF',
  },
  managerIconContainer: {
    backgroundColor: '#F5F3FF',
  },
  superAdminIconContainer: {
    backgroundColor: '#D1FAE5',
  },
  roleInfo: {
    flex: 1,
    marginRight: 12,
  },
  roleTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  roleName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1E293B',
    marginRight: 8,
  },
  roleNameTablet: {
    fontSize: 18,
  },
  systemBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B981',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 4,
  },
  systemBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  roleDescription: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 8,
    lineHeight: 16,
  },
  roleMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 11,
    color: '#64748B',
  },
  roleActions: {
    flexDirection: 'row',
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  viewButton: {
    backgroundColor: '#F1F5F9',
  },
  editButton: {
    backgroundColor: '#F1F5F9',
  },
  deleteButton: {
    backgroundColor: '#FEF2F2',
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  deleteButtonText: {
    color: '#EF4444',
  },
  fab: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#8B5CF6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 8,
  },
  fabTablet: {
    width: 64,
    height: 64,
    borderRadius: 32,
    bottom: 24,
    right: 24,
  },
  loader: {
    marginTop: 60,
  },
  errorContainer: {
    alignItems: 'center',
    marginTop: 60,
    padding: 16,
  },
  errorText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginTop: 12,
    textAlign: 'center',
  },
  errorTextTablet: {
    fontSize: 20,
    marginTop: 16,
  },
  errorSubtext: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
    textAlign: 'center',
  },
  errorSubtextTablet: {
    fontSize: 14,
    marginTop: 6,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8B5CF6',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
    marginTop: 16,
  },
  retryButtonTablet: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 60,
    padding: 16,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 12,
  },
  emptyTextTablet: {
    fontSize: 20,
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 4,
    textAlign: 'center',
  },
  emptySubtextTablet: {
    fontSize: 14,
    marginTop: 6,
  },
  emptyActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8B5CF6',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
    marginTop: 16,
  },
  emptyActionButtonTablet: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
  },
  emptyActionButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  // Create Modal Styles
  createModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  createModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    maxHeight: height * 0.9,
    width: '100%',
  },
  createModalContentTablet: {
    maxHeight: height * 0.9,
    width: isLargeTablet ? '70%' : (isTablet ? '80%' : '100%'),
  },
  createModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  createModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  createModalTitleTablet: {
    fontSize: 24,
  },
  createModalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  createModalSubtitleTablet: {
    fontSize: 14,
    marginTop: 4,
  },
  createModalBody: {
    padding: 20,
    maxHeight: height * 0.7,
  },
  createModalSafeFooter: {
    backgroundColor: '#FFFFFF',
  },
  createModalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    gap: 12,
  },
  roleTypeSelector: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 4,
    marginBottom: 24,
  },
  roleTypeOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 8,
    gap: 8,
  },
  roleTypeOptionSelected: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  roleTypeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  roleTypeTextSelected: {
    color: '#8B5CF6',
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 6,
  },
  inputLabelTablet: {
    fontSize: 16,
    marginBottom: 8,
  },
  requiredStar: {
    color: '#EF4444',
    fontSize: 14,
  },
  inputSubtext: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 12,
  },
  inputSubtextTablet: {
    fontSize: 14,
    marginBottom: 16,
  },
  textInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#1E293B',
  },
  textInputTablet: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    borderRadius: 12,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  textAreaTablet: {
    minHeight: 100,
  },
  departmentGrid: {
    justifyContent: 'space-between',
    gap: 8,
  },
  departmentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '48%',
    minHeight: 60,
  },
  departmentItemTablet: {
    width: isLargeTablet ? '23%' : '31%',
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 64,
  },
  departmentItemSelected: {
    backgroundColor: '#F5F3FF',
    borderColor: '#8B5CF6',
  },
  originalDepartmentItem: {
    borderColor: '#10B981',
  },
  departmentTextContainer: {
    flex: 1,
    marginLeft: 8,
  },
  departmentName: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  departmentNameTablet: {
    fontSize: 14,
  },
  departmentNameSelected: {
    color: '#8B5CF6',
    fontWeight: '600',
  },
  originalDepartmentName: {
    fontWeight: '600',
  },
  departmentModule: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 2,
  },
  departmentModuleTablet: {
    fontSize: 11,
  },
  originalBadge: {
    fontSize: 10,
    color: '#10B981',
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  noDepartments: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  noDepartmentsText: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 8,
    textAlign: 'center',
  },
  managerInfoCard: {
    flexDirection: 'row',
    backgroundColor: '#F5F3FF',
    borderRadius: 10,
    padding: 16,
    marginBottom: 24,
    gap: 12,
    borderWidth: 1,
    borderColor: '#EDE9FE',
  },
  managerInfoContent: {
    flex: 1,
  },
  managerInfoTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 4,
  },
  managerInfoText: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 16,
  },
  permissionsButtonContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    flexWrap: 'wrap',
  },
  permissionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8B5CF6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
    minWidth: 160,
    alignSelf: 'flex-start',
  },
  permissionsButtonTablet: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  permissionsButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  permissionsButtonTextTablet: {
    fontSize: 14,
  },
  permissionsSummary: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginTop: 8,
  },
  departmentSummary: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  departmentSummaryTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 4,
  },
  permissionsListText: {
    fontSize: 11,
    color: '#64748B',
    lineHeight: 16,
  },
  noPermissionsText: {
    fontSize: 11,
    color: '#94A3B8',
    fontStyle: 'italic',
  },
  summaryCard: {
    flexDirection: 'row',
    backgroundColor: '#F5F3FF',
    borderWidth: 1,
    borderColor: '#EDE9FE',
    borderRadius: 12,
    padding: 16,
    gap: 12,
    marginTop: 8,
  },
  summaryContent: {
    flex: 1,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 8,
  },
  summaryDetails: {
    gap: 4,
  },
  summaryText: {
    fontSize: 11,
    color: '#64748B',
  },
  warningCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 10,
    padding: 16,
    gap: 12,
    marginTop: 8,
  },
  warningContent: {
    flex: 1,
  },
  warningTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: 4,
  },
  warningText: {
    fontSize: 12,
    color: '#92400E',
    lineHeight: 16,
  },
  cancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingVertical: 14,
  },
  cancelButtonTablet: {
    borderRadius: 12,
    paddingVertical: 16,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  cancelButtonTextTablet: {
    fontSize: 16,
  },
  submitButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8B5CF6',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 12,
    gap: 6,
    minHeight: 48,
  },
  submitButtonTablet: {
    borderRadius: 12,
    paddingVertical: 16,
    gap: 8,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  submitButtonTextTablet: {
    fontSize: 16,
  },
  // Permission Modal Styles
  permissionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  permissionModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    maxHeight: height * 0.9,
    width: '100%',
  },
  permissionModalContentTablet: {
    maxHeight: height * 0.9,
    width: isLargeTablet ? '70%' : (isTablet ? '80%' : '100%'),
  },
  permissionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  permissionModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  permissionModalTitleTablet: {
    fontSize: 24,
  },
  permissionModalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  permissionModalSubtitleTablet: {
    fontSize: 14,
    marginTop: 4,
  },
  permissionModalBody: {
    padding: 20,
    maxHeight: height * 0.7,
  },
  permissionModalSafeFooter: {
    backgroundColor: '#FFFFFF',
  },
  permissionModalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    gap: 12,
  },
  permissionsSection: {
    marginBottom: 24,
  },
  permissionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  permissionsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
  },
  permissionsTitleTablet: {
    fontSize: 16,
  },
  permissionsModule: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  selectAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  selectAllText: {
    fontSize: 12,
    color: '#64748B',
  },
  selectAllTextSelected: {
    color: '#8B5CF6',
    fontWeight: '600',
  },
  managerPermissionInfo: {
    flexDirection: 'row',
    backgroundColor: '#F5F3FF',
    borderRadius: 10,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: '#EDE9FE',
  },
  managerPermissionText: {
    flex: 1,
    fontSize: 12,
    color: '#64748B',
    lineHeight: 16,
  },
  loadingPermissions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  loadingTextLarge: {
    fontSize: 12,
    color: '#94A3B8',
  },
  loadingTextTablet: {
    fontSize: 14,
  },
  permissionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  permissionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
    maxWidth: width * 0.42,
  },
  permissionChipTablet: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 8,
    maxWidth: width * 0.28,
  },
  permissionChipSelected: {
    backgroundColor: '#F5F3FF',
    borderColor: '#8B5CF6',
  },
  permissionText: {
    fontSize: 11,
    color: '#64748B',
    flexShrink: 1,
  },
  permissionTextTablet: {
    fontSize: 13,
  },
  permissionTextSelected: {
    color: '#8B5CF6',
    fontWeight: '500',
  },
  permissionsCount: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 8,
    textAlign: 'right',
  },
  // Update Modal Styles
  updateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  updateModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    maxHeight: height * 0.9,
    width: '100%',
  },
  updateModalContentTablet: {
    maxHeight: height * 0.9,
    width: isLargeTablet ? '70%' : (isTablet ? '80%' : '100%'),
  },
  updateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  updateModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  updateModalTitleTablet: {
    fontSize: 24,
  },
  updateModalSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  updateModalSubtitleTablet: {
    fontSize: 14,
    marginTop: 4,
  },
  updateModalBody: {
    padding: 20,
    maxHeight: height * 0.7,
  },
  updateModalSafeFooter: {
    backgroundColor: '#FFFFFF',
  },
  updateModalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    gap: 12,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingRoleText: {
    marginTop: 12,
    fontSize: 14,
    color: '#64748B',
  },
  // Role Details Modal Styles
  roleDetailsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  roleDetailsModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    maxHeight: height * 0.9,
    width: '100%',
  },
  roleDetailsModalContentTablet: {
    maxHeight: height * 0.9,
    width: isLargeTablet ? '70%' : (isTablet ? '80%' : '100%'),
  },
  roleDetailsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  roleDetailsTitleContainer: {
    flex: 1,
  },
  roleDetailsModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  roleDetailsModalTitleTablet: {
    fontSize: 24,
  },
  roleDetailsModalSubtitle: {
    fontSize: 14,
    color: '#8B5CF6',
    marginTop: 2,
    fontWeight: '600',
  },
  roleDetailsModalSubtitleTablet: {
    fontSize: 16,
    marginTop: 4,
  },
  roleDetailsModalBody: {
    padding: 20,
  },
  roleDetailsModalSafeFooter: {
    backgroundColor: '#FFFFFF',
  },
  roleDetailsModalFooter: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  closeDetailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 8,
    flex: 1,
  },
  closeDetailsButtonTablet: {
    borderRadius: 12,
    paddingVertical: 14,
    gap: 10,
  },
  closeDetailsButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  closeDetailsButtonTextTablet: {
    fontSize: 16,
  },
  detailsLoader: {
    marginTop: 40,
    marginBottom: 40,
  },
  roleInfoSection: {
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1E293B',
  },
  sectionTitleTablet: {
    fontSize: 18,
  },
  countBadge: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 30,
    alignItems: 'center',
  },
  countBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  roleInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoItem: {
    width: '48%',
    marginBottom: 12,
  },
  fullWidthItem: {
    width: '100%',
  },
  infoLabel: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
  },
  descriptionText: {
    fontWeight: '400',
    lineHeight: 20,
  },
  departmentsGrid: {
    gap: 12,
  },
  departmentChip: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
    alignItems: 'flex-start',
  },
  departmentIcon: {
    marginTop: 2,
    marginRight: 12,
  },
  departmentInfo: {
    flex: 1,
  },
  departmentNameDetails: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 2,
  },
  departmentModuleDetails: {
    fontSize: 12,
    color: '#8B5CF6',
    fontWeight: '500',
    marginBottom: 4,
  },
  departmentDesc: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 16,
  },
  permissionsListContainer: {
    gap: 12,
  },
  permissionRow: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
  },
  permissionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  permissionName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    flex: 1,
    marginRight: 12,
  },
  permissionBadge: {
    backgroundColor: '#EDE9FE',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  permissionBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#7C3AED',
  },
  permissionDescription: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 8,
    lineHeight: 16,
  },
  permissionMeta: {
    flexDirection: 'row',
    gap: 12,
  },
  permissionMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  permissionMetaText: {
    fontSize: 11,
    color: '#64748B',
  },
});

export default styles;